server:
  port: 7400

spring:
  application:
    name: RESERVATION-SERVICE
  data:
    mongodb:
      uri: mongodb://localhost:27017/hotels
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
